version: '2'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    links:
      - db:mysql
    container_name: app_web_1
    depends_on:
      - db
    volumes:
      - my-webvolume:/var/lib/web
    environment:
      - "PYTHONUNBUFFERED:0"
  db:
    image: mysql:5.7
    restart: always
    container_name: app_db_1
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume:
  my-webvolume: