SECRET_KEY = 'you-will-never-guess'
DEBUG=True
DB_USERNAME='root'
DB_PASSWORD='password'
DATABASE_NAME='database'
DB_HOST='mysql'
DB_URI = "mysql+pymysql://%s:%s@%s/%s?charset=utf8mb4" % (DB_USERNAME, DB_PASSWORD, DB_HOST, DATABASE_NAME)
SQLALCHEMY_DATABASE_URI = DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS = True
MYSQL_DATABASE_CHARSET = 'utf8mb4'
SQLALCHEMY_ECHO = True

